---
- hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  become: yes
  become_user: root
  tasks:
    - name: Install python-apt package
      apt: 
        name: python3-apt
        state: present
    - name: site | hello world
      shell: echo " no sugar tonight in my coffee"
    - name: Install NGINX 
      apt:
        name: nginx
        state: present
    - name: ensure NGINX is stopped
      service:
        name: nginx
        state: stopped
    - name: Install Unbound
      apt:
        name: unbound
        state: present
    - name: ensure Unbound is running
      service:
        name: unbound
        state: started    
    - name: Check if NGINX is active
      command: systemctl status nginx
      register: deb_check
      ignore_errors: yes
      no_log: True
      failed_when: false
    - name: Stop NGINX if it is active 
      service:
        name: nginx
        state: stopped
    - name:  Start NGINX up now
      service:
        name: nginx
        state: started

